---
- name: Ensure k9s config dir exists
  ansible.builtin.file:
    path: "~/Library/Application\ Support/k9s/"
    state: directory
    recurse: true
    mode: '0755'
  tags:
    - install

- name: Ensure default skin is installed for k9s
  ansible.builtin.copy:
    src: skin.yml
    dest: "~/Library/Application\ Support/k9s/skin.yml"
    mode: 'u=rw,go=r'
  tags:
    - config