---
- hosts: all

  vars_files:
    - default.config.yaml

  pre_tasks:
    - name: Override default.config.yaml
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/work.config.yaml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: ['osx-cli']
    - role: geerlingguy.mac.homebrew
      tags: ['brew']
    - role: geerlingguy.mac.mas
      when: configure_mas
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: firacode
      when: configure_firacode
      tags: ['firacode']
    - role: iterm2
      when: configure_iterm2
      tags: ['iterm2']
    - role: omz
      when: configure_omz
      tags: ['omz']
    - role: ssh
      when: configure_ssh
      tags: ['ssh']
    - role: tmux
      when: configure_tmux
      tags: ['tmux']
    - role: vim
      when: configure_vim
      tags: ['vim']
    - role: vscode
      when: configure_vscode
      tags: ['vscode']

  tasks:
    - import_tasks: tasks/extra-packages.yaml
      tags: ['extra-packages']

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']