vscode:
  extensions:
    - golang.go
    - Gruntfuggly.todo-tree
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.powershell
    - ms-vsliveshare.vsliveshare
    - redhat.ansible
    - redhat.vscode-yaml
    - samuelcolvin.jinjahtml